name: Update Unity project semantic versioning

on:
  push:
    branches:
      - main
      - feature

jobs:
  semver:
    name: Update semver
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          sparse-checkout: ProjectSettings.asset
          sparse-checkout-cone-mode: false

      - name: Determine semver update type based on branch
        id: determine-semver-update
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "::set-output name=semver-update-type::minor"
          elif [[ ${{ github.ref }} == 'refs/heads/feature' ]]; then
            echo "::set-output name=semver-update-type::patch"
          fi

      - name: Find ProjectSettings.asset & increment its bundleVersion number
        uses: AlexStormwood/UnityAutomatedSemver@v1.1.1
        id: semver-update
        with:
          semver-update-type: ${{ steps.determine-semver-update.outputs.semver-update-type }} 
          project-settings-path: 'ProjectSettings/ProjectSettings.asset'
          should-add-ms-store-trailing-zero: true

      - name: Get the new semver number
        run: echo "The new semver number for this Unity project is ${{ steps.semver-update.outputs.semver-number }}"

      - name: Push changed files back to repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: update semantic version to ${{ steps.semver-update.outputs.semver-number }}"
          git push origin HEAD:${{ github.ref }}
